#
# Most of these settings are taken from here:
# https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml
#

version: 1.0.{build}

build: off

cache:
  - '%LOCALAPPDATA%\pip\Cache'
  - memcached -> appveyor.yml

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\.ci\\run_with_env.cmd"
    RELATE_LOCAL_TEST_SETTINGS: "local_settings_example.py"

  matrix:
    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.
    # See: https://www.appveyor.com/docs/windows-images-software/#python

    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.x"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  - appveyor DownloadFile "http://s3.amazonaws.com/downloads.northscale.com/memcached-win64-1.4.4-14.zip" -FileName memcached.zip
  - 7z x memcached.zip -y
  - ps: $Memcached = Start-Process memcached\memcached.exe -PassThru

  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  # - "pip install --disable-pip-version-check --user --upgrade pip"

  - "git submodule update --init --recursive"

  # Update pip/setuptools/wheel to avoid an issue like
  # https://github.com/HearthSim/decrunch/issues/3
  # e.g. https://ci.appveyor.com/project/inducer/relate/build/1.0.936
  - "%CMD_IN_ENV% python -m pip install --upgrade pip setuptools wheel"

  # Install poetry for packaging
  - "%CMD_IN_ENV% python -m pip install poetry"

  # Install requirements
  - "%CMD_IN_ENV% poetry install"

test_script:
  # Run the project tests
  - "%CMD_IN_ENV% poetry run pytest --cov=."

after_test:
  - "%CMD_IN_ENV% poetry run codecov -X gcov"
